export enum OrderStatus {
  NEW = 'NEW',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_FAIL = 'PAYMENT_FAIL',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  DELIVERED = 'DELIVERED',
  CANCELED = 'CANCELED',
}
